version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/flask-app

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      runas: ubuntu
